language: node_js
node_js:
  - "6.17"
env:
  global:
    secure: "p8U1p1e/cEvgDo+rE6PK3+M/A4htbPSE2Np7DBPok3KZZItuI0amI7ttSnPGhRtTDO5wwfJtGk5WZod6dcOtH9G6TEZUi2Fa9za/9JVLsumGM8wUFLxwAnZu23I0oXn4BPZQ2rkx6ThjrV7kmWroYPBu9gFM911+mORiNzDrn67RH7GMnSBYzXsuMZGh4NjIJLriogdLUtCgQJHYJ7D/Qlcwz7gRKBZcs8gdgZNk5/gA9Ajh9iw4DBnPOsISZVq7aZ0bxQsLxCfsDFb/Sh2pfTF55Vhbm1euBPsVHiUBiPFryfKHrEET3AkUXLTPuxhB+WsDNrmf7ntGG4BvDVxXHc2hx+tPcGjPD7TBBrJvQD4atv17S94JcqSGCoxWrDWtohp1mhl0eZbNqPJy0bmg/+KxP0npZ99QL/DJignlk+j4m/3y5Smr2E6FUQqx+SqjF0tK+/QlplnDrDqdhQ7Uum5hxhY/oQSYjDip6byCLVgAGFfaTkCW3eI1UsK6MlATXZ+wRUAi//P+97ppZoMOVJIkq738TurC3tcdOrZaTY2HnP1pRu8IMnj7oG5DE1AyN3y3FzW6ixm+/WL5shjb0skB6lYZbLvPZaHDLXwTDncJJTj5NY5Ha9Ry2E3X8mLRekeCwb+hIPaDx8k7t2WmduaUwUOFqEkuYihy5c/SdWs="
cache:
  directories:
  - $HOME/calibre-bin
sudo: false
before_script:
  - export PATH=$PATH:$HOME/calibre-bin/calibre
  - >
    which calibre ||
    wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py |
    python -c "import sys; main=lambda x,y:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main('~/calibre-bin', True)"
script:
  - npm i
  - npm run archive
after_success:
  - ./.ci/update-gh-pages.sh > /dev/null 2>&1
notifications:
  email:
    on_success: never
    on_failure: never
